export enum GpFormFieldType {
  CALENDAR = 'gp-form-calendar-field',
  CHECKBOX = 'gp-form-checkbox-field',
  DROPDOWN = 'gp-form-dropdown-field',
  DROPDOWN_RELATED = 'gp-form-dropdown-related-field',
  FILE = 'gp-form-file-field',
  FILE_B64 = 'gp-form-b64-file-field',
  IMG = 'gp-form-img-field',
  NUMBER = 'gp-form-number-field',
  SWITCH = 'gp-form-switch-field',
  TEXT = 'gp-form-text-field',
  TEXT_AREA = 'gp-form-textarea-field',
  TIME = 'gp-form-time-field',
  WYSIWYG = 'gp-form-wysiwyg-field',
  NULLABLE_CHECKBOX = 'gp-form-nullable-checkbox-field',
  COLOR_PICKER = 'gp-form-color-picker-field',
  PASSWORD = 'gp-form-password-field',
  DAYS_OF_WEEK = 'gp-form-days-of-week-field',
}
