import { CommonRs } from './../../../../gp-all-component/src/lib/services/core/common.service';
import { MainMenuServiceMock } from './../../../../gp-all-component/src/lib/components/main-menu/main-menu.mock';
import { MainMenuProviderService } from './../../../../gp-all-component/src/lib/services/api/main-menu/main-menu-provider.service';
import { MenuRq } from './../../../../gp-all-component/src/lib/services/api/main-menu/main-menu.service';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';

@Injectable()
export class MainMenuTesterService extends MainMenuProviderService {
    menu = new MainMenuServiceMock().menu;

    temp = [];

    getEstructuraMenu(): any[] {
        this.temp = [
            {
                id: 'FROFR001',
                texto: 'Reservas',
                description: 'Consulta de reservas',
                type: 'A',
                icon: 'search',
                action: 'reservas',
                enabled: false,
                overview: 'dashboard',
            },
            {
                id: 'FROFR001B',
                texto: 'Reservas360',
                description: 'Consulta de reservas',
                type: 'A',
                icon: 'search',
                action: 'reservas360',
                enabled: false,
                overview: 'dashboard',
            },
            {
                id: 'concierge-service',
                texto: 'Concierge Service',
                description: 'Concierge Service',
                type: 'A',
                icon: 'concierge',
                enabled: false,
                submenus: [
                    {
                        id: 'CLDFR029A',
                        texto: 'Movimientos',
                        description: 'Movimientos',
                        type: 'Q',
                        icon: 'search',
                        enabled: false,
                        action: 'movimientos-concierge',
                        overview: 'overview-concierge',
                    },
                    {
                        id: 'CLDFR029B',
                        texto: 'Movimientos360',
                        description: 'Movimientos',
                        type: 'Q',
                        icon: 'search',
                        enabled: true,
                        action: 'movimientos-concierge360',
                        overview: 'overview-concierge',
                    },
                    {
                        id: 'cd_mantenimientos',
                        texto: 'Mantenimientos',
                        description: 'Mantenimientos',
                        type: 'MF',
                        icon: 'maintenance-folder',
                        enabled: false,
                        submenus: [
                            {
                                id: 'CLDFR028A',
                                texto: 'Alertas',
                                description: 'Alertas',
                                type: 'M',
                                icon: 'maintenance',
                                enabled: false,
                                action: 'tablas/CdEale',
                            },
                            {
                                id: 'CLDFR026A',
                                texto: 'Clasificación',
                                description: 'Clasificación',
                                type: 'M',
                                icon: 'maintenance',
                                enabled: false,
                                action: 'tablas/CdEcla',
                            },
                            {
                                id: 'CLDFR027A',
                                texto: 'Departamentos',
                                description: 'Departamentos',
                                type: 'M',
                                icon: 'maintenance',
                                enabled: false,
                                action: 'mantenimientos/concierge',
                            },
                            {
                                id: 'CLDFR035A',
                                texto: 'Solicitudes por Hotel',
                                description: 'Solicitudes por Hotel',
                                type: 'M',
                                icon: 'maintenance',
                                enabled: false,
                                action: 'mantenimientos/solicitud-hotel',
                            },
                            {
                                id: 'CLDFR035B',
                                texto: 'Solicitudes por Hotel 360',
                                description: 'Solicitudes por Hotel',
                                type: 'M',
                                icon: 'maintenance',
                                enabled: true,
                                action: 'mantenimientos/solicitud-hotel360',
                            },
                        ],
                    },
                    {
                        id: 'cd_listados',
                        texto: 'Listados',
                        description: 'Listados',
                        type: 'LF',
                        icon: 'list-folder',
                        enabled: false,
                        submenus: [
                            {
                                id: 'CLDRW031',
                                texto: 'Comparativo Hoteles',
                                description: 'Comparativo Hoteles',
                                type: 'L',
                                icon: 'list',
                                enabled: false,
                                action: 'listado/comparativo-hoteles',
                            },
                            {
                                id: 'CLDRW031B',
                                texto: 'Comparativo Hoteles 360',
                                description: 'Comparativo Hoteles',
                                type: 'L',
                                icon: 'list',
                                enabled: true,
                                action: 'listado/comparativo-hoteles360',
                            },
                            {
                                id: 'CLDRW032',
                                texto: 'Dpto. y Solicitudes',
                                description: 'Dpto. y Solicitudes',
                                type: 'L',
                                icon: 'list',
                                enabled: false,
                                action: 'listado/departamento-solicitudes',
                            },
                            {
                                id: 'CLDRW032B',
                                texto: 'Dpto. y Solicitudes 360',
                                description: 'Dpto. y Solicitudes',
                                type: 'L',
                                icon: 'list',
                                enabled: true,
                                action: 'listado/departamento-solicitudes360',
                            },
                        ],
                    },
                ],
            },
            {
                id: 'clientes',
                texto: 'Clientes',
                description: 'Clientes',
                type: 'A',
                icon: 'contacts',
                enabled: false,
                submenus: [
                    {
                        id: 'CRMFR004A',
                        texto: 'Consulta',
                        description: 'Consulta',
                        type: 'Q',
                        icon: 'search',
                        enabled: false,
                        action: 'consulta-cliente',
                    },
                    {
                        id: 'CRMFR001A',
                        texto: 'Ficha',
                        description: 'Ficha',
                        icon: 'search',
                        type: 'Q',
                        enabled: false,
                        action: 'ficha-cliente',
                    },
                    {
                        id: 'CRMFR004A2',
                        texto: 'Consultas Antiguas',
                        description: 'Consultas Antiguas',
                        type: 'QF',
                        icon: 'search-folder',
                        enabled: false,
                        overview: 'overview',
                        submenus: [
                            {
                                id: 'CRMFR004A2',
                                texto: 'Consulta (Old)',
                                description: 'Consulta (Old)',
                                type: 'Q',
                                icon: 'search',
                                enabled: false,
                                action: 'consulta-cliente-old',
                            },
                            {
                                id: 'CRMFR001A2',
                                texto: 'Ficha (Old)',
                                description: 'Ficha (Old)',
                                type: 'Q', // En un futuro puede que se mueva y pase a aplicación
                                icon: 'search',
                                enabled: false,
                                action: 'ficha-cliente-old',
                            },
                        ],
                    },
                    {
                        id: 'CRMFR019A1',
                        texto: 'Funcionalidades',
                        description: 'Funcionalidades',
                        type: 'FF',
                        icon: 'funcionality-folder',
                        enabled: false,
                        submenus: [
                            {
                                id: 'CRMFR019A',
                                texto: 'Inserción receptivo',
                                description: 'Inserción receptivo',
                                type: 'F',
                                icon: 'funcionality',
                                enabled: false,
                                action: 'insercion-receptivo',
                            },
                            {
                                id: 'CRMFR020A',
                                texto: 'Importación contactos',
                                description: 'Importación contactos',
                                type: 'F',
                                icon: 'funcionality',
                                enabled: false,
                                action: 'carga-contactos',
                            },
                        ],
                    },
                    {
                        id: 'cd_mantenimientos',
                        texto: 'Mantenimientos',
                        description: 'Mantenimientos',
                        type: 'MF',
                        icon: 'maintenance-folder',
                        enabled: false,
                        submenus: [
                            {
                                id: 'cd_mantenimientos',
                                texto: 'Básicos',
                                description: 'Mant. Básicos',
                                type: 'MF',
                                icon: 'maintenance-folder',
                                enabled: false,
                                submenus: [
                                    {
                                        id: 'CRMFR002A',
                                        texto: 'Nacionalidades',
                                        description: 'Nacionalidades',
                                        type: 'M',
                                        icon: 'maintenance',
                                        enabled: false,
                                        action: 'tablas/CrmNaci',
                                    },
                                    {
                                        id: 'CRMFR005A',
                                        texto: 'Visto promoción',
                                        description: 'Visto promoción',
                                        type: 'M',
                                        icon: 'maintenance',
                                        enabled: false,
                                        action: 'tablas/CrmVipo',
                                    },
                                    {
                                        id: 'CRMFR023A',
                                        texto: 'Canales',
                                        description: 'Canales',
                                        type: 'M',
                                        icon: 'maintenance',
                                        enabled: false,
                                        action: 'mantenimientos/canales',
                                    },
                                    {
                                        id: 'CRMFR033A',
                                        texto: 'Alertas de control',
                                        description: 'Alertas de control',
                                        type: 'M',
                                        icon: 'maintenance',
                                        enabled: false,
                                        action: 'tablas/CrmAler',
                                    },
                                    {
                                        id: 'CRMFR040A',
                                        texto: 'Pref. Documentación',
                                        description: 'Pref. Documentación',
                                        type: 'M',
                                        icon: 'maintenance',
                                        enabled: false,
                                        action: 'tablas/CrmPrdo',
                                    },
                                    {
                                        id: 'CRMFR043A',
                                        texto: 'Mails Informativos',
                                        description: 'Mails Informativos',
                                        type: 'M',
                                        icon: 'maintenance',
                                        enabled: false,
                                        action: 'tablas/CrmDoem',
                                    },
                                ],
                            },
                            {
                                id: 'cd_mantenimientos',
                                texto: 'Fidelización CF',
                                description: 'Fidelización CF',
                                type: 'MF',
                                icon: 'maintenance-folder',
                                enabled: false,
                                submenus: [
                                    {
                                        id: 'CRMFR034A',
                                        texto: 'Agrup. preferencias',
                                        description: 'Agrup. preferencias',
                                        type: 'M',
                                        icon: 'maintenance',
                                        enabled: false,
                                        action: 'tablas/CrmPrag',
                                    },
                                    {
                                        id: 'CRMFR035A',
                                        texto: 'Preferencias',
                                        description: 'Preferencias',
                                        type: 'M',
                                        icon: 'maintenance',
                                        enabled: false,
                                        action: 'mantenimientos/preferencias',
                                    },
                                    {
                                        id: 'CRMFR041A',
                                        texto: 'Pref. Pais Destino',
                                        description: 'Pref. Pais Destino',
                                        type: 'M',
                                        icon: 'maintenance',
                                        enabled: false,
                                        action: 'tablas/CrmPrpa',
                                    },
                                    {
                                        id: 'CRMFR038A',
                                        texto: 'Benef. Fidelizacion',
                                        description: 'Benef. Fidelizacion',
                                        type: 'M',
                                        icon: 'maintenance',
                                        enabled: false,
                                        action: 'mantenimientos/beneficios',
                                    },
                                    {
                                        id: 'CRMFR037A',
                                        texto: 'Nivel Fidelizacion',
                                        description: 'Nivel Fidelizacion',
                                        type: 'M',
                                        icon: 'maintenance',
                                        enabled: false,
                                        action: 'mantenimientos/fidelizacion',
                                    },
                                    {
                                        id: 'CRMFR042A',
                                        texto: 'Clientes Fid. GTI',
                                        description: 'Clientes Fid. GTI',
                                        type: 'M',
                                        icon: 'maintenance',
                                        enabled: false,
                                        action: 'tablas/CrmCgti',
                                    },
                                ],
                            },
                        ],
                    },
                    {
                        id: 'CRM_LIST',
                        texto: 'Listados',
                        description: 'Listados',
                        type: 'LF',
                        icon: 'list-folder',
                        enable: false,
                        submenus: [
                            {
                                id: 'CRMFR012A',
                                texto: 'Estadisticas por entrada',
                                description: 'Estadisticas por entrada',
                                type: 'L',
                                icon: 'list',
                                enabled: false,
                                action: 'listado/estadisticas-entradas',
                            },
                        ],
                    },
                ],
            },
            {
                id: 'servicios',
                texto: 'Servicios',
                description: 'Servicios',
                type: 'A',
                icon: 'services',
                enabled: false,
                submenus: [
                    {
                        id: 'SERFR215A',
                        texto: 'Consulta Reservas',
                        description: 'Consulta Reservas',
                        type: 'Q',
                        icon: 'search',
                        enabled: false,
                        action: 'reserva-servicios',
                        overview: 'overview-reserva-servicios',
                    },
                    {
                        id: 'cd_mantenimientos',
                        texto: 'Mantenimientos',
                        description: 'Mantenimientos',
                        type: 'MF',
                        icon: 'maintenance-folder',
                        enabled: false,
                        submenus: [
                            {
                                id: 'cd_mantenimientos',
                                texto: 'Básicos',
                                description: 'Mant. Básicos',
                                type: 'MF',
                                icon: 'maintenance-folder',
                                enabled: false,
                                submenus: [
                                    {
                                        id: 'SERFR209A',
                                        texto: 'Hoteles App',
                                        description: 'Hoteles App',
                                        type: 'M',
                                        icon: 'maintenance',
                                        enabled: false,
                                        action: 'tablas/SvcHoap',
                                    },
                                    {
                                        id: 'SERFR211A',
                                        texto: 'Imágenes App',
                                        description: 'Imágenes App',
                                        type: 'M',
                                        icon: 'maintenance',
                                        enabled: false,
                                        action: 'mantenimientos/imagenes',
                                    },
                                    {
                                        id: 'SERFR034A',
                                        texto: 'Usuarios / hotel (cal)',
                                        description: 'Usuarios / hotel (cal)',
                                        type: 'M',
                                        icon: 'maintenance',
                                        enabled: false,
                                        action: 'mantenimientos/usuarios-calidad',
                                    },
                                    {
                                        id: 'CRMFR008A',
                                        texto: 'Usuarios / hotel (crm)',
                                        description: 'Usuarios / hotel (crm)',
                                        type: 'M',
                                        icon: 'maintenance',
                                        enabled: false,
                                        action: 'mantenimientos/usuarios-crm',
                                    },
                                    {
                                        id: 'SERFR216A',
                                        texto: 'Origenes OC',
                                        description: 'Origenes OC',
                                        type: 'M',
                                        icon: 'maintenance',
                                        enabled: false,
                                        action: 'tablas/BpgOori',
                                    },
                                    {
                                        id: 'SERFR217A',
                                        texto: 'Pildoras OC',
                                        description: 'Pildoras OC',
                                        type: 'M',
                                        icon: 'maintenance',
                                        enabled: false,
                                        action: 'tablas/BpgOpil',
                                    },
                                    {
                                        id: 'SERFR218A',
                                        texto: 'Configuración OC',
                                        description: 'Configuración OC',
                                        type: 'M',
                                        icon: 'maintenance',
                                        enabled: false,
                                        action: 'tablas/BpgOcho',
                                    },
                                ],
                            },
                            {
                                id: 'actividades',
                                texto: 'Actividades',
                                description: 'Actividades',
                                type: 'MF',
                                icon: 'maintenance-folder',
                                enabled: false,
                                submenus: [
                                    {
                                        id: 'SERFR201A',
                                        texto: 'Departamentos',
                                        description: 'Departamentos',
                                        type: 'M',
                                        icon: 'maintenance',
                                        enabled: false,
                                        action: 'tablas/SvcDept',
                                    },
                                    {
                                        id: 'SERFR203A',
                                        texto: 'Programas',
                                        description: 'Programas',
                                        type: 'M',
                                        icon: 'maintenance',
                                        enabled: false,
                                        action: 'mantenimientos/programas',
                                    },
                                    {
                                        id: 'SERFR206A',
                                        texto: 'Actividades',
                                        description: 'Actividades',
                                        type: 'M',
                                        icon: 'maintenance',
                                        enabled: false,
                                        action: 'mantenimientos/actividades',
                                    },
                                    {
                                        id: 'SERFR204A',
                                        texto: 'Actividades Hotel',
                                        description: 'Actividades Hotel',
                                        type: 'M',
                                        icon: 'maintenance',
                                        enabled: false,
                                        action: 'mantenimientos/actividades-hotel',
                                    },
                                ],
                            },
                            {
                                id: 'ubicaciones',
                                texto: 'Ubicaciones',
                                description: 'Ubicaciones',
                                type: 'MF',
                                icon: 'maintenance-folder',
                                enabled: false,
                                submenus: [
                                    {
                                        id: 'SERFR202A',
                                        texto: 'Ubicaciones',
                                        description: 'Ubicaciones',
                                        type: 'M',
                                        icon: 'maintenance',
                                        enabled: false,
                                        action: 'mantenimientos/ubicaciones',
                                    },
                                    {
                                        id: 'SERFR208A',
                                        texto: 'Tipos de Ubicaciones',
                                        description: 'Tipos de Ubicaciones',
                                        type: 'M',
                                        icon: 'maintenance',
                                        enabled: false,
                                        action: 'tablas/SvcTubi',
                                    },
                                ],
                            },
                            {
                                id: 'servicios',
                                texto: 'Servicios',
                                description: 'Servicios',
                                type: 'MF',
                                icon: 'maintenance-folder',
                                enabled: false,
                                submenus: [
                                    {
                                        id: 'SERFR007A',
                                        texto: 'Servicios',
                                        description: 'Servicios',
                                        type: 'M',
                                        icon: 'maintenance',
                                        enabled: false,
                                        action: 'mantenimientos/servicios',
                                    },
                                    {
                                        id: 'SERFR034A',
                                        texto: 'Tipos de Servicio',
                                        description: 'Tipos de Servicios',
                                        type: 'M',
                                        icon: 'maintenance',
                                        enabled: false,
                                        action: 'tablas/SvcTips',
                                    },
                                    {
                                        id: 'SERFR061A',
                                        texto: 'Tipos de Serv. Hotel',
                                        description: 'Tipos de Serv. Hotel',
                                        type: 'M',
                                        icon: 'maintenance',
                                        enabled: false,
                                        action: 'mantenimientos/tipos-servicios-hotel',
                                    },
                                    {
                                        id: 'SERFR060A',
                                        texto: 'Directorio de Servicios',
                                        description: 'Directorio de Servicios',
                                        type: 'M',
                                        icon: 'maintenance',
                                        enabled: false,
                                        action: 'mantenimientos/directorio-servicios',
                                    },
                                    {
                                        id: 'SERFR001A',
                                        texto: 'Turnos',
                                        description: 'Turnos',
                                        type: 'M',
                                        icon: 'maintenance',
                                        enabled: false,
                                        action: 'mantenimientos/turnos',
                                    },
                                    {
                                        id: 'SERFR210A',
                                        texto: 'Planning',
                                        description: 'Planning',
                                        type: 'M',
                                        icon: 'maintenance',
                                        enabled: false,
                                        action: 'mantenimientos/planning',
                                    },
                                    {
                                        id: 'SERFR035A',
                                        texto: 'Tipos de Restaurante',
                                        description: 'Tipos de Restaurante',
                                        type: 'M',
                                        icon: 'maintenance',
                                        enabled: false,
                                        action: 'tablas/SvcTire',
                                    },
                                ],
                            },
                        ],
                    },
                ],
            },
            {
                id: 'cambio_divisas',
                texto: 'Cambio Divisas',
                description: 'cambio_divisas',
                type: 'A',
                icon: 'currency-exchange',
                enabled: false,
                submenus: [
                    {
                        id: 'DVFR002A',
                        texto: 'Consulta',
                        description: 'Consulta',
                        type: 'Q',
                        icon: 'search',
                        enabled: false,
                        action: 'currency-exchange-search',
                    },
                    {
                        id: 'DVFR001A',
                        texto: 'Cambio Divisas',
                        description: 'Cambio Divisas',
                        type: 'F',
                        icon: 'funcionality',
                        enabled: false,
                        action: 'currency-exchange',
                    },
                ],
            },
            {
                id: 'encuestas',
                texto: 'Encuestas',
                description: 'Encuestas',
                type: 'A',
                icon: 'funcionality',
                enabled: false,
                submenus: [
                    {
                        id: 'BPGFR001A',
                        texto: 'Mantenimiento Encuestas',
                        description: 'Mantenimiento Encuestas',
                        type: 'M',
                        icon: 'maintenance',
                        enabled: false,
                        action: 'mantenimientos/encuestas',
                    },
                    {
                        id: 'BPGFR002A',
                        texto: 'Encuestas',
                        description: 'Encuestas',
                        type: 'F',
                        icon: 'funcionality',
                        enabled: false,
                        action: 'encuestas',
                    },
                ],
            },
            {
                id: 'configuracion',
                texto: 'Configuracion',
                description: 'Configuracion',
                type: 'MF',
                icon: 'config',
                enabled: false,
                submenus: [
                    {
                        id: 'FROFR002',
                        texto: 'Reservas pasadas y futuras',
                        description: 'Reservas pasadas y futuras',
                        type: 'Q',
                        icon: 'search',
                        action: 'reservas-new',
                        enabled: false,
                    },
                    {
                        id: 'cd_mantenimientos',
                        texto: 'Mantenimientos',
                        description: 'Mantenimientos',
                        type: 'MF',
                        icon: 'maintenance-folder',
                        enabled: false,
                        submenus: [
                            {
                                id: 'WCOFR003A',
                                texto: 'Agentes',
                                description: 'Agentes',
                                type: 'M',
                                icon: 'maintenance',
                                enabled: false,
                                action: 'mantenimientos/agentes',
                            },
                        ],
                    },
                    {
                        id: 'seguridad',
                        texto: 'Seguridad',
                        description: 'Seguridad',
                        type: 'MF',
                        icon: 'config',
                        enabled: false,
                        submenus: [
                            {
                                id: 'SECFR002A',
                                texto: 'Mantenimiento CA',
                                description: 'Mantenimiento CA',
                                type: 'M',
                                icon: 'maintenance',
                                enabled: false,
                                action: 'tablas/CaUsuario',
                            },
                            {
                                id: 'SECFR001A',
                                texto: 'Mantenimiento General',
                                description: 'Mantenimiento General',
                                type: 'M',
                                icon: 'maintenance',
                                enabled: false,
                                action: 'seguridad',
                            },
                        ],
                    },
                    {
                        id: 'inhouse',
                        texto: 'Inhouse',
                        description: 'Inhouse',
                        type: 'FF',
                        icon: 'inhouse',
                        enabled: false,
                        submenus: [
                            {
                                id: 'INHFR001A',
                                texto: 'Inhouse',
                                description: 'Inhouse',
                                type: 'F',
                                icon: 'funcionality',
                                enabled: false,
                                action: 'inhouse',
                            },
                        ],
                    },
                    {
                        id: 'marketing',
                        texto: 'BP Mkt',
                        description: 'BP Mkt',
                        type: 'MF',
                        icon: 'bpmkt',
                        enabled: false,
                        submenus: [
                            {
                                id: 'CRMFR053A',
                                texto: 'BP Datos Básicos',
                                description: 'BP Datos Básicos',
                                type: 'M',
                                icon: 'maintenance',
                                enabled: false,
                                action: 'mantenimientos/canal-dispo',
                            },
                            {
                                id: 'CRMFR052A',
                                texto: 'BP Schedule',
                                description: 'BP Schedule',
                                type: 'M',
                                icon: 'maintenance',
                                enabled: false,
                                action: 'mantenimientos/terminal-schedule',
                            },
                            {
                                id: 'CRMFR051A',
                                texto: 'BP Programas',
                                description: 'BP Programas',
                                type: 'M',
                                icon: 'maintenance',
                                enabled: false,
                                action: 'mantenimientos/marketing',
                            },
                            {
                                id: 'CRMFR050A',
                                texto: 'BP Directo',
                                description: 'BP Directo',
                                type: 'M',
                                icon: 'maintenance',
                                enabled: false,
                                action: 'mantenimientos/contenido',
                            },
                        ],
                    },
                ],
            },
        ];
        return this.temp;
    }

    obtenOpcionesActivas(rq: MenuRq = null): Observable<CommonRs> {
        const response: any = new CommonRs();
        response.ok = true;
        response.menu = this.menu;
        return Observable.of(response);
    }
}
