export enum GpTableRestrictions {
    NOT_NULL = 'NOT_NULL',
    MAX_LENGTH = 'MAX_LENGTH',
    MIN_LENGTH = 'MIN_LENGTH',
    MAX_VALUE = 'MAX_VALUE',
    MIN_VALUE = 'MIN_VALUE',
    LIST_ALLOWED_VALUES = 'LIST_ALLOWED_VALUES',
}
